name: Publicar imagen Docker en GHCR

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: alexisr-dev/frontend_restaurante

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v7

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login en GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build y push de la imagen
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            VITE_API_DJANGO=${{ vars.VITE_API_DJANGO }}
            VITE_API_FASTAPI=${{ vars.VITE_API_FASTAPI }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
